name: Deploy Scrap Management System

on:
  push:
    branches:
      - feature/deploytest-1
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
   
      - name: Checkout code
        uses: actions/checkout@v4

 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/scrap-management-system:latest .

     
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/scrap-management-system:latest

     
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Scrap-Management-System

            echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" > .env
            echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env

            docker pull ${{ secrets.DOCKER_USERNAME }}/scrap-management-system:latest

            docker stop scrap-management-system || true
            docker rm scrap-management-system || true

            docker run -d \
              --name scrap-management-system \
              -p 80:80 \
              --env-file .env \
              ${{ secrets.DOCKER_USERNAME }}/scrap-management-system:latest
